name: compile and upload artifact for UNIX-file systems

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Create build directory
        run: mkdir build

      - name: Init cmake
        run: cmake -S . -B build

      - name: Build cmake
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Terminal-File-Explorer
          path: build/TerminalFileExplorer
          overwrite: true